In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("data2.csv")
X = dataset[["Open"]]
y = dataset[["Close Price"]]

In [3]:
from sklearn.ensemble import RandomForestRegressor

In [4]:
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X, y)

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [5]:
y_pred = regressor.predict(X)

In [6]:
from sklearn.metrics import r2_score
r2 = r2_score(y , y_pred)

In [7]:
print(r2)

0.8980613795071977


In [8]:
regressor.predict([[12274.90]])

array([1546.6])

In [9]:
regressor.predict([[12269.25]])

array([1546.6])

In [10]:
regressor.predict([[969.95]])

array([1068.365])

In [11]:
regressor.predict([[11447.8]])

array([2300.93])

In [12]:
regressor.predict([[11538.45]])

array([2087.62])

In [13]:
regressor.predict([[11581.05]])# 18 september

array([2112.505])